### ISSUE TITLE
Nihongokyoshi grammar dict missing Entry for 〜上で（〜てから）

### ISSUE THREAD

**Issue by kuroahna** [aiko-tanaka/Grammar-Dictionaries#1]
Hey, great dictionary. I was using it earlier and I found that when I was hovering over 上で, I only see [・〜上で（目的）](https://nihongokyoshi-net.com/2019/05/15/jlptn2-grammar-uede-2/) but not [〜上で（〜てから）](https://nihongokyoshi-net.com/2019/05/26/jlptn2-grammar-uede-3/)

![image](https://user-images.githubusercontent.com/85209455/166165363-32cca590-3a15-4a48-a221-0cd81088679e.png)

どんなときどう使う 日本語表現文型辞典 does have an entry

**Comment by aiko-tanaka** [comment]
indeed, not sure what happened but my script might have failed to access that specific entry or i might have accidentally deleted it (probably the script tho). 

I might update some entries in bulk in the future (maybe by scanning for missing entries using a script?) but not for now.

**Comment by aiko-tanaka** [comment]
Already updated
