### ISSUE TITLE
Add edewakaru grammar dictionary

### ISSUE THREAD

**Issue by kuroahna** [aiko-tanaka/Grammar-Dictionaries#2]
Hi, thanks for the amazing grammar dictionaries for Yomichan. Just wanted to raise an issue for some visibility to create a grammar dictionary for [edewakaru](https://www.edewakaru.com/archives/cat_179055.html) in case anyone's interested in doing so.

Might be nice to add it under the README

```
Here are a few of the sites that I think would be worth looking into:
* https://jn1et.com/jlpt/
* https://nihon5-bunka.net/japanese-grammars/
* https://japanese-bank.com/jlpt-grammar-all/
* https://itazuraneko.neocities.org/grammar/masterreference.html#handbook
* https://www.edewakaru.com/archives/cat_179055.html
```

**Comment by aiko-tanaka** [comment]
Already made one a few days ago, might release it after a few weeks after a few finishing touches (mostly adding deconjugation info).

**Comment by aiko-tanaka** [comment]
uploaded

**Comment by kuroahna** [comment]
Doing God's work my friend, thank you, really appreciate these grammar dictionaries (and with deconjugation support!), huge game changer
